theme: jekyll-theme-minimal
logo: logosubkro_200.png
description: Centro de buceo en Tarragona Subkro. Cursos SSI (Open Water, Advance), bautizos de mar. Buceo con atunes en la Ametlla de Mar. Buceo recreativo y técnico.
